### ISSUE TITLE
Sim-to-real Transfer

### ISSUE THREAD

**Issue by DaveDe** [DeepRoboticsLab/Lite3_MotionSDK#3]
I'm wondering if there are any implementations of transferring a locomotion policy trained in simulation to hardware. I trained locomotion policies with the Lite3 in Isaac Gym, which are saved as PyTorch policies. Is there any existing code to transfer this to hardware? If not, does there exist any python wrapper for the Lite3 motion API? 

Thanks!

**Comment by yyang0802** [comment]
The development of Lite3 motion sdk for Python is ongoing. Please stay updated by checking our website or following our social media platforms for future announcements.
